apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-nginx
spec:
  ingressClassName: nginx
  rules:
  - host: 2048.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: 2048
            port:
              number: 80
