apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-2048
spec:
  ingressClassName: "2048"
  rules:
  - host: 2048.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: 2048
            port:
              number: 80
